---

- name: Install nodegear services
  hosts: nodegear_services
  user: root
  vars:
    redis_ip: 198.27.127.39
    redis_port: 6379
    mongo_ip: 198.27.127.39
    backend_ip: 198.27.70.69
  tasks:
    - include: tasks/firewall.yml
    - { include: tasks/nginx_conf.yml, shortname: "ng_frontend", domains: "nodegear.io www.nodegear.io", nginx_ip: 198.27.127.39, port: 9117 }
    - include: tasks/services.yml