---

- name: NG Redis
  ufw: rule=allow direction=in proto=any src="{{ backend_ip }}" port="{{ redis_port }}" dest="{{ redis_ip }}"

- name: NG Mongodb
  ufw: rule=allow direction=in proto=any src="{{ backend_ip }}" port=27017 dest="{{ mongo_ip }}"

- name: Run Nodegear MySQL
  docker: image="tutum/mysql" ports="198.27.127.39:3306:3306" volumes="/home/ng_mysql:/var/lib/mysql" name="ng_mysql_db" state=running

- name: Download Redis Docker
  git: repo=git://github.com/CastawayLabs/redis-docker.git dest=/tmp/redis-docker

- name: Build Redis Docker
  docker_image: path="/tmp/redis-docker" name="castawaylabs/redis-docker" state=present

- name: Run NodeGear Redis
  docker: image="castawaylabs/redis-docker" ports="198.27.127.39:6379:6379" name="ng_redis" volumes="/home/ng_redis:/var/lib/redis" state=running

- name: Download Mongodb Docker
  git: repo=git://github.com/CastawayLabs/mongodb-docker.git dest=/tmp/mongodb-docker

- name: Build Mongodb Docker
  docker_image: path="/tmp/mongodb-docker" name="castawaylabs/mongodb-docker" state=present

- name: Run NodeGear Mongodb
  docker: image="castawaylabs/mongodb-docker" volumes="/home/ng_mongodb:/var/lib/mongodb" ports="198.27.127.39:27017:27017" name="ng_mongodb" state=running
