---

- name: Install backend upstart script
  copy: src=backend.conf dest=/etc/init/nodegear_backend.conf

- name: Install git upstart script
  copy: src=git.conf dest=/etc/init/nodegear_git.conf

- name: Install monitrc
  copy: src=monitrc dest=/etc/monit/monitrc backup=yes

- name: Install monit backend config
  copy: src=backend_monit dest=/etc/monit/conf.d/nodegear_backend

- name: Install monit git config
  copy: src=git_monit dest=/etc/monit/conf.d/nodegear_git

- name: Reload monit
  service: name=monit state=restarted